import './styles.css';
import logo from './icon.png';
console.log("Successfuly loaded index.js");
const navButtons = document.querySelector('.navButtons');
const iconDiv = document.createElement('div');
navButtons.before(iconDiv);
const icon = document.createElement('img');
icon.src=logo;
iconDiv.appendChild(icon);
icon.classList.add('logo');
const contentDiv = document.querySelector('#content');
const contentHighLight = document.createElement('div');
contentDiv.appendChild(contentHighLight);
const mainLogo = document.createElement('div');
const logoHeadings = document.createElement('div');
contentHighLight.appendChild(mainLogo);
contentHighLight.appendChild(logoHeadings);
const mainImage = document.createElement('img');
mainImage.src=logo;
mainLogo.appendChild(mainImage);
mainImage.classList.add('mainImage');